### ISSUE TITLE
broken spin1_api.h

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/spinnaker_tools#157]
Commit 49e1eaacf2a14c46d4d907c6ea04c9d6bded248b broke the build, as it introduced changes to spin1_api.h that the Perl preprocessor can't convert into assembler constants.

**Comment by dkfellows** [comment]
Note that this means that the QA for #155 was lacking. No idea exactly how.

**Comment by rowleya** [comment]
The build currently appears to work on all tools that test it... is there an example where it breaks?

**Comment by dkfellows** [comment]
Something weird's going on with my setup; I'm investigating further.

**Comment by dkfellows** [comment]
Ah. False alarm. It was a wrong version of the perl tools for converting `.h` &rarr; `.s` &rarr; `.gas`, and it was producing bad code (and not cleaning up).
