### ISSUE TITLE
SCAMP: Don't throw away packets on send

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/spinnaker_tools#68]
When a core sends an SDP packet, it copies it to the SDP system RAM buffer and then notifies SCAMP.  When SCAMP processes the notification, it first tries to allocate a local SDP buffer; if this fails, it throws away the SDP packet, but it still tell the core that it has processed it.  It would be better to leave the message box busy; the core can then time-out waiting for the message to be sent, and choose itself whether it should be thrown away or retried.

**Comment by lplana** [comment]
This issue can be closed. It was addressed in pull request #73:

* The changes in this pull request will cause a call to **spin1_send_sdp_msg()** to return FAILURE if the monitor cannot allocate a local buffer to hold the message. Currently, the monitor silently drops the message and **spin1_send_sdp_msg()** returns SUCCESS.

* There is no attempt to re-send a failed message, this is left to the application code.
